name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Path to the directory containing docker-compose.yml
        file: docker-compose.yml  # Path to your docker-compose.yml
        platforms: linux/amd64  # Adjust platforms as needed
        push: true
        tags: vivekdjoshi/bw_backend_piping:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: SSH to server and execute commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker-compose -f ./docker-compose.yml down
          docker-compose -f ./docker-compose.yml pull
          docker-compose -f ./docker-compose.yml up -d
